package com.jeremylakeyjr.lanbulab.service

import com.jeremylakeyjr.lanbulab.data.model.SliceSettings
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

class SlicingService {
    
    /**
     * Slices a 3D model file with given settings
     * Creates a basic G-code file for demonstration purposes
     */
    suspend fun sliceModel(
        modelFile: File,
        settings: SliceSettings,
        outputDir: File
    ): File? = withContext(Dispatchers.IO) {
        try {
            if (!outputDir.exists()) {
                outputDir.mkdirs()
            }
            
            val outputFileName = modelFile.nameWithoutExtension + "_sliced.gcode"
            val outputFile = File(outputDir, outputFileName)
            
            // Generate basic G-code
            val gcode = generateBasicGcode(modelFile.name, settings)
            outputFile.writeText(gcode)
            
            outputFile
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
    
    /**
     * Generates a basic G-code file with proper header and settings
     * This is a simplified version for demonstration - real slicing would be much more complex
     */
    private fun generateBasicGcode(modelName: String, settings: SliceSettings): String {
        return buildString {
            // G-code header
            appendLine("; Generated by Lanbulab")
            appendLine("; Model: $modelName")
            appendLine("; Filament Type: ${settings.filamentType}")
            appendLine("; Layer Height: ${settings.layerHeight}mm")
            appendLine("; Infill: ${settings.infillDensity}%")
            appendLine("; Bed Temp: ${settings.bedTemperature}°C")
            appendLine("; Nozzle Temp: ${settings.nozzleTemperature}°C")
            appendLine("; Print Speed: ${settings.printSpeed}%")
            appendLine("; Supports: ${if (settings.supportEnabled) "Yes" else "No"}")
            appendLine()
            
            // Start G-code
            appendLine("; Start G-code")
            appendLine("G28 ; Home all axes")
            appendLine("M140 S${settings.bedTemperature} ; Set bed temperature")
            appendLine("M104 S${settings.nozzleTemperature} ; Set nozzle temperature")
            appendLine("M190 S${settings.bedTemperature} ; Wait for bed temperature")
            appendLine("M109 S${settings.nozzleTemperature} ; Wait for nozzle temperature")
            appendLine("G92 E0 ; Reset extruder")
            appendLine("G1 Z2.0 F3000 ; Move Z up")
            appendLine("G1 X10 Y10 F5000 ; Move to start position")
            appendLine()
            
            // Prime line
            appendLine("; Prime line")
            appendLine("G1 Z0.3 F3000")
            appendLine("G1 X10 Y100 E15 F1500 ; Draw prime line")
            appendLine("G1 X10.4 Y100 F5000")
            appendLine("G1 X10.4 Y10 E30 F1500 ; Draw prime line")
            appendLine("G92 E0 ; Reset extruder")
            appendLine()
            
            // Main print layers (simplified)
            appendLine("; Main print")
            appendLine("; NOTE: This is a simplified G-code for demonstration")
            appendLine("; In production, this would contain actual model geometry")
            var currentZ = settings.layerHeight
            val layers = 50 // Simplified example with 50 layers
            
            for (layer in 0 until layers) {
                appendLine("; Layer $layer")
                appendLine("G1 Z${String.format("%.2f", currentZ)} F5000")
                
                // Simplified perimeter
                appendLine("G1 X50 Y50 F${settings.printSpeed * 30}")
                appendLine("G1 X100 Y50 E2")
                appendLine("G1 X100 Y100 E2")
                appendLine("G1 X50 Y100 E2")
                appendLine("G1 X50 Y50 E2")
                
                currentZ += settings.layerHeight
            }
            
            appendLine()
            
            // End G-code
            appendLine("; End G-code")
            appendLine("M104 S0 ; Turn off nozzle")
            appendLine("M140 S0 ; Turn off bed")
            appendLine("G91 ; Relative positioning")
            appendLine("G1 E-2 F2700 ; Retract")
            appendLine("G1 Z10 F3000 ; Move Z up")
            appendLine("G90 ; Absolute positioning")
            appendLine("G28 X Y ; Home X and Y")
            appendLine("M84 ; Disable motors")
            appendLine("; Print complete!")
        }
    }
    
    /**
     * Validates if a file can be sliced
     */
    fun canSliceFile(file: File): Boolean {
        val supportedExtensions = listOf("3mf", "stl", "obj")
        return file.extension.lowercase() in supportedExtensions
    }
    
    /**
     * Gets default slice settings for a given filament type
     */
    fun getDefaultSettings(filamentType: String): SliceSettings {
        return when (filamentType.uppercase()) {
            "PLA" -> SliceSettings(
                layerHeight = 0.2f,
                infillDensity = 15,
                printSpeed = 100,
                bedTemperature = 60,
                nozzleTemperature = 220,
                filamentType = "PLA"
            )
            "ABS" -> SliceSettings(
                layerHeight = 0.2f,
                infillDensity = 15,
                printSpeed = 80,
                bedTemperature = 100,
                nozzleTemperature = 240,
                filamentType = "ABS"
            )
            "PETG" -> SliceSettings(
                layerHeight = 0.2f,
                infillDensity = 15,
                printSpeed = 80,
                bedTemperature = 80,
                nozzleTemperature = 230,
                filamentType = "PETG"
            )
            else -> SliceSettings()
        }
    }
}
